# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thread-Signal
version:      1.07
version_from: lib/Thread/Signal.pm
installdirs:  site
requires:
    load:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
